---
- name: Create a Simple VM provision
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Recording VM size for small
      ansible.builtin.set_fact:
        num_cpus: 1
        memory_mb: 2048
      when: '"small" in survey_size | default("small")'

    - name: Recording VM size for medium
      ansible.builtin.set_fact:
        num_cpus: 2
        memory_mb: 4024
      when: '"medium" in survey_size | default("small")'

    - name: Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        datacenter: "Datacenter"
        folder: /aap-testing
        state: poweredon
        template: "ubuntu-test-template"
        validate_certs: false
        name: "{{ survey_name | default('ubuntu-test') }}"
        wait_for_ip_address: true
        hardware:
          num_cpus: "{{ num_cpus }}"
          memory_mb: "{{ memory_mb }}"
        networks:
          - name: VM Network
            type: dhcp
            connected: true
            start_connected: true
        customization:
          domain: "lab.test"
          dns_servers:
            - 192.168.0.20

